# Generated by Django 5.0.7 on 2024-09-04 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="Categorie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("images", models.ImageField(blank=True, upload_to="images")),
            ],
            options={"verbose_name": "Categorie", "verbose_name_plural": "Categories"},
        ),
        migrations.CreateModel(
            name="Produit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code_barre", models.CharField(max_length=30, unique=True)),
                ("nom_prod", models.CharField(max_length=80)),
                ("date_fabrication", models.DateField(null=True)),
                ("date_peremption", models.DateField(null=True)),
                (
                    "fournisseur",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("emplacement_prod", models.CharField(blank=True, max_length=60)),
                ("quantite", models.IntegerField()),
                ("prix", models.FloatField()),
                ("images", models.ImageField(blank=True, upload_to="images")),
            ],
            options={"verbose_name": "Produit", "verbose_name_plural": "Produits"},
        ),
        migrations.CreateModel(
            name="Commande",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite", models.IntegerField(default=1)),
                ("ordered", models.BooleanField(default=False)),
                ("paid", models.BooleanField(default=False)),
                ("date_commande", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="achats.produit"
                    ),
                ),
            ],
            options={"verbose_name": "Commande", "verbose_name_plural": "Commandes"},
        ),
        migrations.CreateModel(
            name="Paiement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant_paie", models.FloatField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("methode_paie", models.CharField(max_length=50)),
                ("etat_paie", models.BooleanField(default=False)),
                (
                    "code_verification",
                    models.CharField(default="000000", max_length=6, unique=True),
                ),
                ("phone", models.CharField(max_length=20)),
                ("nom_du_client", models.CharField(max_length=80)),
                ("verification", models.BooleanField(default=False)),
                ("verifieur", models.CharField(default="null", max_length=60)),
                ("id_verifieur", models.CharField(default="null", max_length=15)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"verbose_name": "Paiement", "verbose_name_plural": "Paiements"},
        ),
        migrations.CreateModel(
            name="Panier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("commande", models.ManyToManyField(to="achats.commande")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"verbose_name": "Panier", "verbose_name_plural": "Paniers"},
        ),
        migrations.CreateModel(
            name="SousCategorie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("images", models.ImageField(blank=True, upload_to="images")),
                (
                    "categorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="achats.categorie",
                    ),
                ),
            ],
            options={
                "verbose_name": "SousCategorie",
                "verbose_name_plural": "SousCategories",
            },
        ),
        migrations.AddField(
            model_name="produit",
            name="sous_categorie",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="achats.souscategorie",
            ),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("caissiere", "Caissiere"),
                            ("standard", "Standard"),
                            ("tablette", "Tablette"),
                            ("admin", "Admin"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
