# Generated by Django 5.0.6 on 2024-07-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0002_commande_user_paiement_user_panier_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panier',
            name='date_commande',
        ),
        migrations.RemoveField(
            model_name='panier',
            name='ordered',
        ),
        migrations.AddField(
            model_name='commande',
            name='date_commande',
            field=models.DateTimeField(null=True),
        ),
    ]
