# Generated by Django 5.0.7 on 2024-09-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("achats", "0002_remove_produit_images")]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="otp",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="otp_expiry",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
