# Generated by Django 5.0.6 on 2024-07-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0003_remove_panier_date_commande_remove_panier_ordered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date_commande',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
