# Generated by Django 5.0.7 on 2024-10-10 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("achats", "0003_userprofile_otp_userprofile_otp_expiry")]

    operations = [migrations.DeleteModel(name="UserProfile")]
