# Generated by Django 5.0.6 on 2024-07-03 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0004_alter_commande_date_commande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='etat_paie',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='methode_paie',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='montant_paie',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='ref_trans',
            field=models.CharField(max_length=60),
        ),
    ]
