# Generated by Django 5.0.7 on 2024-10-17 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("achats", "0004_delete_userprofile")]

    operations = [
        migrations.AlterField(
            model_name="produit",
            name="sous_categorie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="achats.souscategorie",
            ),
        )
    ]
