# Generated by Django 5.0.7 on 2024-10-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("achats", "0005_alter_produit_sous_categorie")]

    operations = [
        migrations.AddField(
            model_name="produit",
            name="taille",
            field=models.CharField(blank=True, max_length=20),
        )
    ]
