# Generated by Django 5.0.6 on 2024-07-03 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0006_commande_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='code_verification',
            field=models.CharField(default='000000', max_length=6, unique=True),
        ),
    ]
