# Generated by Django 5.0.7 on 2024-10-17 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("achats", "0006_produit_taille")]

    operations = [migrations.RemoveField(model_name="produit", name="taille")]
