# Generated by Django 5.0.7 on 2024-10-18 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("achats", "0008_fournisseur")]

    operations = [
        migrations.AlterField(
            model_name="produit",
            name="fournisseur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="achats.fournisseur",
            ),
        )
    ]
