# Generated by Django 5.0.7 on 2024-10-18 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("achats", "0009_alter_produit_fournisseur")]

    operations = [migrations.RemoveField(model_name="produit", name="fournisseur")]
