# Generated by Django 5.0.6 on 2024-07-04 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0009_alter_produit_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='phone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
