# Generated by Django 5.0.6 on 2024-07-06 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0010_paiement_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='etat',
        ),
    ]
