# Generated by Django 5.0.6 on 2024-07-08 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0011_remove_produit_etat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='identifiant',
            new_name='code_barre',
        ),
    ]
