# Generated by Django 5.0.7 on 2024-10-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("achats", "0012_remove_produit_fournisseur_delete_fournisseur")]

    operations = [
        migrations.CreateModel(
            name="Fournisseur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=30)),
                ("prenom", models.CharField(max_length=80)),
                ("date_de_creation", models.DateTimeField(auto_now_add=True)),
                ("Adresse", models.CharField(max_length=60)),
                ("numero_telephone", models.CharField(max_length=30)),
            ],
            options={
                "verbose_name": "Fournisseur",
                "verbose_name_plural": "Fournisseurs",
            },
        )
    ]
