# Generated by Django 5.0.6 on 2024-07-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0012_rename_identifiant_produit_code_barre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='sous_categorie',
        ),
        migrations.AddField(
            model_name='produit',
            name='fournisseur',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
