# Generated by Django 5.0.6 on 2024-07-08 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0013_remove_produit_sous_categorie_produit_fournisseur'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SousCategorie',
        ),
    ]
