# Generated by Django 5.0.6 on 2024-07-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0014_delete_souscategorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='nom_du_client',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
    ]
