# Generated by Django 5.0.7 on 2024-10-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("achats", "0014_produit_fournisseur")]

    operations = [
        migrations.AlterField(
            model_name="produit",
            name="date_fabrication",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="produit",
            name="date_peremption",
            field=models.DateTimeField(null=True),
        ),
    ]
