# Generated by Django 5.0.7 on 2024-10-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("achats", "0015_alter_produit_date_fabrication_and_more")]

    operations = [
        migrations.AddField(
            model_name="paiement",
            name="date_verif",
            field=models.DateTimeField(null=True),
        )
    ]
