# Generated by Django 5.0.6 on 2024-07-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0015_paiement_nom_du_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='verification',
            field=models.BooleanField(default=False),
        ),
    ]
