# Generated by Django 5.0.6 on 2024-07-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0016_paiement_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='id_verifieur',
            field=models.CharField(default='null', max_length=15),
        ),
        migrations.AddField(
            model_name='paiement',
            name='verifieur',
            field=models.CharField(default='null', max_length=60),
        ),
    ]
