# Generated by Django 5.0.7 on 2024-10-22 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achats", "0017_alter_categorie_images_alter_souscategorie_images_and_more")
    ]

    operations = [
        migrations.AddField(
            model_name="commande",
            name="paiement",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commandes",
                to="achats.paiement",
            ),
            preserve_default=False,
        )
    ]
