# Generated by Django 5.0.7 on 2024-10-22 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("achats", "0018_commande_paiement")]

    operations = [
        migrations.AlterField(
            model_name="commande",
            name="paiement",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commandes",
                to="achats.paiement",
            ),
        )
    ]
