# Generated by Django 5.0.7 on 2024-10-22 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("achats", "0019_alter_commande_paiement")]

    operations = [migrations.RemoveField(model_name="commande", name="paiement")]
