# Generated by Django 5.0.7 on 2024-10-23 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("achats", "0020_remove_commande_paiement")]

    operations = [
        migrations.AddField(
            model_name="commande",
            name="paiement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="achats.paiement",
            ),
        )
    ]
