# Generated by Django 5.0.7 on 2024-10-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("achats", "0021_commande_paiement")]

    operations = [
        migrations.AlterField(
            model_name="commande",
            name="date_commande",
            field=models.DateTimeField(auto_now_add=True, null=True),
        )
    ]
