# Generated by Django 5.0.7 on 2024-11-02 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("achats", "0022_alter_commande_date_commande")]

    operations = [
        migrations.AddField(
            model_name="produit",
            name="statut",
            field=models.CharField(default="Stock", max_length=20),
        )
    ]
