# Generated by Django 5.0.7 on 2024-11-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("achats", "0023_produit_statut")]

    operations = [
        migrations.AddField(
            model_name="commande",
            name="prix_unitaire",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        )
    ]
