# Generated by Django 5.0.7 on 2024-11-19 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("achats", "0025_alter_commande_prix_unitaire")]

    operations = [
        migrations.AlterField(
            model_name="commande",
            name="prix_unitaire",
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        )
    ]
