# Generated by Django 5.0.7 on 2024-11-20 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("achats", "0026_alter_commande_prix_unitaire")]

    operations = [
        migrations.AlterField(
            model_name="commande", name="prix_unitaire", field=models.FloatField()
        )
    ]
