# Generated by Django 5.0.7 on 2024-11-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("achats", "0028_historiquepaiement")]

    operations = [
        migrations.AlterField(
            model_name="historiquepaiement",
            name="qr_image",
            field=models.ImageField(max_length=50, unique=True, upload_to=""),
        )
    ]
