# Generated by Django 5.0.7 on 2024-11-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("achats", "0029_alter_historiquepaiement_qr_image")]

    operations = [
        migrations.AlterField(
            model_name="historiquepaiement",
            name="qr_image",
            field=models.CharField(max_length=50, unique=True),
        )
    ]
