# Generated by Django 5.0.7 on 2024-12-01 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0030_alter_historiquepaiement_qr_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='souscategorie',
            name='images',
        ),
    ]
